### ISSUE TITLE
Not recognizing a Hung server

### ISSUE THREAD

**Issue by darkarks** [msniveau/discord-statusbotv2#1] opened 2019-07-14 18:43 UTC
Not recognizing a Hung server because server is responding to queries but the process is hung - generally not an issue the bot could detect i think. However, when the server is brought down while in this state the bot doesn't recognize it has gone offline - nor will it recognize when the server comes back online after that.

**Comment by msniveau** [comment] 2019-08-12 12:52
The bot is just using the communication through the protocol this game uses (steam for example), so if the server still reports to the serverlist its all fine for the bot. If you have a specific case and an idea how to check if it hung please let me know little more details :)

You enabled the monitoring of the server? Can you provide more details and how to reproduce?

**Comment by darkarks** [comment] 2019-08-12 19:08
Yes, monitoring was enabled. Specifically the server had crashed into hung processes so the server reported and the bot didn't detect it was down. But ONLY in these situation the bot would not recognize when we manually brought the server down on this hang. So even after an hour if being down the bot wouldn't report it was down. Then when we brought the server back online it would not recognize that the server was now online (assuming because its last known status was still up). I can't really give you more than that. It worked perfect outside of that hung process on the server. We've moved on from the bot so I can't help much more. Good luck!

**Comment by msniveau** [comment] 2019-08-16 12:53
Hung gameservers may still report to the serverlist. The bot is using a simple query for fetching the gameservers details. If there is the need I may can implement some other states, but they're game specific and needs some work.

If you want some special hung detection feature please provide the game used and how to get a gameserver in that state. For further discussion you may also join on discord, since chatting is lot more easy :D https://discord.gg/aMDa2TB

Closing this issue since the owner of this ticket isn't using this bot anymore.

**Closed by msniveau** 2019-08-16 12:53 UTC
